language: node_js

node_js:
  - "0.8"
  - "0.10"
  - "0.12"

branches:
  except:
    - gh-pages

before_install:
    - if [[ `node --version` == *v0.8* ]]; then npm install -g npm; fi

sudo: false
cache:
  directories:
    - node_modules
